/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { ShaderMaterial } from 'three'
import { ReactNode } from 'react'

type GLTFResult = GLTF & {
  nodes: {
    ['Box004_01_-_Default_0']: THREE.Mesh
    ['Box005_01_-_Default_0']: THREE.Mesh
    ['Box006_01_-_Default_0']: THREE.Mesh
    ['Box007_01_-_Default_0']: THREE.Mesh
    ['Box009_01_-_Default_0']: THREE.Mesh
    ['Box010_01_-_Default_0']: THREE.Mesh
    Plane: THREE.Mesh
  }
  materials: {
    ['01_-_Default']: THREE.MeshStandardMaterial
  }
}

export function RiverModel(AllProps: JSX.IntrinsicElements['group'] & { waterMaterial?: ReactNode }) {
  const { nodes, materials } = useGLTF('/assets/river.gltf') as GLTFResult
  const { waterMaterial, ...props } = AllProps
  materials['01_-_Default'].transparent = false
  materials['01_-_Default'].opacity = 0.5
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[8.83, 6.31, -138.72]} rotation={[-Math.PI / 2, 0, 0]} scale={0.84}>
            <mesh castShadow receiveShadow geometry={nodes['Box004_01_-_Default_0'].geometry} material={materials['01_-_Default']} />
          </group>
          <group position={[122.39, 8.74, -15.55]} rotation={[-Math.PI / 2, 0, Math.PI]}>
            <mesh castShadow receiveShadow geometry={nodes['Box005_01_-_Default_0'].geometry} material={materials['01_-_Default']} />
          </group>
          <group position={[-60.74, -8.72, -11.6]} rotation={[-1.97, 0.09, -0.03]} scale={1.52}>
            <mesh castShadow receiveShadow geometry={nodes['Box006_01_-_Default_0'].geometry} material={materials['01_-_Default']} />
          </group>
          <group position={[72.12, -5.13, 38.93]} rotation={[-1.44, -0.11, 1.86]} scale={1.45}>
            <mesh castShadow receiveShadow geometry={nodes['Box007_01_-_Default_0'].geometry} material={materials['01_-_Default']} />
          </group>
          <group position={[-47.79, -3.46, -43.99]} rotation={[-1.77, 0.16, -0.74]} scale={[1.16, 1.52, 1.52]}>
            <mesh castShadow receiveShadow geometry={nodes['Box009_01_-_Default_0'].geometry} material={materials['01_-_Default']} />
          </group>
          <group position={[-37.6, 4.67, 175.92]} rotation={[-Math.PI / 2, 0, -1.48]} scale={[1.33, 1.33, 0.78]}>
            <mesh castShadow receiveShadow geometry={nodes['Box010_01_-_Default_0'].geometry} material={materials['01_-_Default']} />
          </group>
        </group>
      </group>
      <mesh
        castShadow
        receiveShadow
        // geometry={nodes.Plane.geometry }
        material={nodes.Plane.material}
        position={[0, 0.14, -0.17]}
        scale={[0.95, 0.8, 2.36]}
        rotation={[-Math.PI/2, 0, 0]}
      >
        <planeBufferGeometry args={[2, 6.2, 100, 100]}  />
        {waterMaterial}
      </mesh>
    </group>
  )
  
  
}

useGLTF.preload('/assets/river.gltf')
